/*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
* NOTE: this file is generated by search_00_generate.py
*
* Make changes there and run in this directory:
*
* > python search_00_generate.py
*
*/

#include <cuvs/neighbors/vecflow.hpp>
#include <cuvs/neighbors/shared_resources.hpp>
#include "../vecflow_search.cuh"

namespace cuvs::neighbors::vecflow {

#define instantiate_search_vecflow_d(data_t) \
 void search( \
	 shared_resources::configured_raft_resources& res, \
	 cuvs::neighbors::vecflow::index<data_t>& index, \
	 raft::device_matrix_view<const data_t, int64_t> queries, \
	 raft::device_vector_view<uint32_t, int64_t> query_labels, \
	 int itopk_size, \
	 raft::device_matrix_view<uint32_t, int64_t> neighbors, \
	 raft::device_matrix_view<float, int64_t> distances) \
 { \
    cuvs::neighbors::vecflow::search<data_t>( \
      res, index, queries, query_labels, itopk_size, neighbors, distances); \
  }

instantiate_search_vecflow_d(float);
#undef instantiate_search_vecflow_d

void search_multi_gpu(shared_resources::configured_raft_resources& res,
                      cuvs::neighbors::vecflow::multi_gpu_index<float>& index,
                      raft::device_matrix_view<const float, int64_t> queries,
                      raft::device_vector_view<uint32_t, int64_t> query_labels,
                      int itopk_size,
                      raft::device_matrix_view<uint32_t, int64_t> neighbors,
                      raft::device_matrix_view<float, int64_t> distances)
{
  cuvs::neighbors::vecflow::search_multi_gpu_impl(
    res, index, queries, query_labels, itopk_size, neighbors, distances);
}

}  // namespace cuvs::neighbors::vecflow
